package entity;

public enum StatType {
    VITA, ATTACK, DIFESA, VELOCITA, ELUSIONE, PRECISIONE, EFFICIENZA,
    FIRE_ATK, FIRE_DEF,
    WATER_ATK, WATER_DEF,
    ELECTRIC_ATK, ELECTRIC_DEF,
    EARTH_ATK, EARTH_DEF,
    WIND_ATK, WIND_DEF,
    LIGHT_ATK, LIGHT_DEF
}
